num = int(input("Enter a number "))
print(num)
dec1 = float(num)
print(dec1)
dec = float(input("Enter a float value "))
print(dec)
num1 = int(dec)
print(num1)
stringg = str(input("enter a string value "))
print(stringg)
list1= list(stringg)
print(list1)
listt= list(input("Enter list values "))
print(listt)            
set1= set(listt)
print(set1)            
sett= set(input("Enter set values "))
print(sett)            
tuple1= tuple(sett)
print(tuple1)            
tuplee= tuple(input("Enter tuple values "))
print(tuplee)                      
diction = dict(input("enter key value pairs "))
print(diction)            
